stages:
  - lint
  - build
  - test

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  allow_failure: true
  script:
    golangci-lint run

build:
  stage: build
  needs: []
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  # variables:
  #   DOCKER_HOST: tcp://docker:2375
  script:
    - docker build -t orders_service:latest ./
    - docker build -t tests:latest -f ./build/integrationTests/Dockerfile ./

test:
  stage: test
  services:
    - name: docker:dind
      alias: docker
  script:
    - cp ./env.example .env
    - docker compose -f ./deployments/integrationTests/docker-compose.yml up -d
    - docker run --network=integrationtests_deployments_service_network --name test-container tests:latest
    - docker compose -f ./deployments/integrationTests/docker-compose.yml up down
    - docker rm -f test-container