version: '3.8'

services:
  postgres:
    image: postgres:15.1
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_test" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - deployments_service_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 1s
      retries: 3
    restart: unless-stopped
    networks:
      - deployments_service_network

  backend:
    image: orders_service
    ports:
      - "8080"
      - "50051"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: db_test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      HTTP_PORT: 8080
      GRPC_PORT: 50051
    networks:
      - deployments_service_network
  nginx:
    image: nginx:latest
    build: ./build/nginx
    env_file:
      - .env
    ports:
      - "80"
    volumes:
      - ./build/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - deployments_service_network

# volumes:
#   postgres_data:
#   redis_data:

networks:
  deployments_service_network: