GRPC_PORT: 50051
POSTGRES:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: big_chungus
  POSTGRES_DB: mydb

  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 5
